name: On release
on:
    release:
        types: [released]
jobs:
  call-shared-workflow:
    uses: Tsjippy/shared-functionality/.github/workflows/reusable.yml@bb278a151a087f4b6ac0908f44c987560b29bf1e