name: On release
on:
    release:
        types: [released]
jobs:
  call-shared-workflow:
    uses: Tsjippy/shared-functionality/.github/workflows/reusable.yml@e605cde307c4c5cea677e7a7c168246bea28af3b