name: On release
on:
    release:
        types: [released]
jobs:
  call-shared-workflow:
    uses: Tsjippy/tsjippy-shared-functionality/.github/workflows/reusable.yml@ff93b9686000be094122e4e770584534e4af82e3